services:
  php:
    build: .
    container_name: saas-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - core
      - proxy

  nginx:
    image: nginx:alpine
    container_name: saas-app-nginx
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - proxy         # keep proxy first
      - core

    labels:
      - traefik.enable=true

      # ðŸ‘‡ Ensure Traefik uses the proxy network
      - traefik.docker.network=proxy

      # Router: domain for your API
      - traefik.http.routers.expense_api.rule=Host(`saas-app.madush.dev`)
      - traefik.http.routers.expense_api.entrypoints=websecure
      - traefik.http.routers.expense_api.tls=true
      - traefik.http.routers.expense_api.tls.certresolver=le

      # Service: nginx listens on port 80 internally
      - traefik.http.services.expense_api.loadbalancer.server.port=80

networks:
  proxy:
    external: true
  core:
    external: true
