services:
  php:
    user: "${UID}:${GID}"
    build: .
    container_name: saas-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - core
      - proxy

  node-build:
    image: node:20
    container_name: saas-app-node
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    # optional:
    # environment:
    #   - NODE_ENV=production
    command: sh -lc "npm install && npm run build"
    networks:
      - proxy

  nginx:
    image: nginx:alpine
    container_name: saas-app-nginx
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./docker-prod/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - proxy         # keep proxy first
      - core

    labels:
      - traefik.enable=true

      # ðŸ‘‡ Ensure Traefik uses the proxy network
      - traefik.docker.network=proxy


      # Router: domain for your API
      - traefik.http.routers.saas_app.rule=Host(`saas-app.madush.dev`)
      - traefik.http.routers.saas_app.entrypoints=websecure
      - traefik.http.routers.saas_app.tls=true
      - traefik.http.routers.saas_app.tls.certresolver=le

      # Service: nginx listens on port 80 internally
      - traefik.http.services.saas_app.loadbalancer.server.port=80

networks:
  proxy:
    external: true
  core:
    external: true

